/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.DBHelper;
import backend.Penyewaan;
import backend.PenyewaanDetail;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;


/**
 *
 * @author HYPE AMD
 */
public class FrmPenyewaan extends javax.swing.JFrame {
    
    // ===== Field tambahan (di luar bagian generated NetBeans) =====
    private List<PenyewaanDetail> listDetail;
    private DefaultTableModel modelDetail;
    private final SimpleDateFormat sdfTampil = new SimpleDateFormat("dd/MM/yyyy");
    private final SimpleDateFormat sdfSql = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

    public FrmPenyewaan() {
        initComponents();
        setupTambahan();
    }   
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNoSewa = new javax.swing.JTextField();
        tglTransaksi = new javax.swing.JTextField();
        txtCatatan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        trfKendaraan = new javax.swing.JTextField();
        TrfSupir = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetail = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        cmbKendaraan = new javax.swing.JComboBox<>();
        cmbPelanggan = new javax.swing.JComboBox<>();
        cmbSopir = new javax.swing.JComboBox<>();
        btnTambahDetail = new javax.swing.JButton();
        btnHapusDetail = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        txtTglMulai = new javax.swing.JFormattedTextField();
        txtTglKembali = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("No Sewa");

        jLabel2.setText("Tanggal Transaksi");

        jLabel3.setText("Pelanggan");

        jLabel4.setText("Tanggal Mulai");

        jLabel5.setText("Tanggal Kembali");

        jLabel6.setText("Catatan");

        txtNoSewa.setEnabled(false);
        txtNoSewa.addActionListener(this::txtNoSewaActionPerformed);

        tglTransaksi.addActionListener(this::tglTransaksiActionPerformed);

        txtCatatan.addActionListener(this::txtCatatanActionPerformed);

        jLabel7.setText("Kendaraan");

        jLabel8.setText("Supir");

        jLabel9.setText("Tarif Kendaraan");

        jLabel10.setText("Tarif Supir");

        trfKendaraan.setEnabled(false);
        trfKendaraan.addActionListener(this::trfKendaraanActionPerformed);

        TrfSupir.setEnabled(false);

        tblDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDetail.setShowGrid(true);
        jScrollPane1.setViewportView(tblDetail);

        jLabel11.setText("Total");

        txtTotal.addActionListener(this::txtTotalActionPerformed);

        cmbKendaraan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbPelanggan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPelanggan.addActionListener(this::cmbPelangganActionPerformed);

        cmbSopir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnTambahDetail.setText("Tambah Kendaraan");
        btnTambahDetail.addActionListener(this::btnTambahDetailActionPerformed);

        btnHapusDetail.setText("Hapus Kendaraan");
        btnHapusDetail.addActionListener(this::btnHapusDetailActionPerformed);

        btnClear.setText("Clear");

        btnSimpan.setText("Simpan");

        txtTglMulai.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("##/##/####"))));

        txtTglKembali.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("##/##/####"))));
        txtTglKembali.addActionListener(this::txtTglKembaliActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(26, 26, 26)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 399, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cmbKendaraan, 0, 151, Short.MAX_VALUE)
                                        .addComponent(cmbSopir, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(trfKendaraan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TrfSupir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTglMulai, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tglTransaksi)
                                        .addComponent(txtCatatan)
                                        .addComponent(cmbPelanggan, 0, 150, Short.MAX_VALUE)
                                        .addComponent(txtNoSewa))
                                    .addComponent(txtTglKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTambahDetail)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapusDetail)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNoSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tglTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTglMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTglKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtCatatan, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbSopir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(trfKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TrfSupir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahDetail)
                    .addComponent(btnHapusDetail)
                    .addComponent(btnClear))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(btnSimpan)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNoSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoSewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoSewaActionPerformed

    private void tglTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglTransaksiActionPerformed

    private void txtCatatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCatatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCatatanActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnTambahDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahDetailActionPerformed
        // TODO add your handling code here:
        tambahKendaraan();
    }//GEN-LAST:event_btnTambahDetailActionPerformed

    private void btnHapusDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusDetailActionPerformed
        // TODO add your handling code here:
        hapusKendaraan();
    }//GEN-LAST:event_btnHapusDetailActionPerformed

    private void trfKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trfKendaraanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trfKendaraanActionPerformed

    private void txtTglKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTglKembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTglKembaliActionPerformed

    private void cmbPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPelangganActionPerformed

    // ===== Setup tambahan (di luar initComponents, aman dari GUI builder) =====

    private void setupTambahan() {
        listDetail = new ArrayList<>();

        // Field read-only
        txtNoSewa.setEditable(false);
        tglTransaksi.setEditable(false);
        trfKendaraan.setEditable(false);
        TrfSupir.setEditable(false);
        txtTotal.setEditable(false);

        // Ganti model tabel jadi 6 kolom sesuai kebutuhan
        String[] kolom = {"Kendaraan", "Supir", "Lama Hari", "Tarif Kendaraan", "Tarif Supir", "Subtotal"};
        modelDetail = new DefaultTableModel(kolom, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblDetail.setModel(modelDetail);

        // btnClear & btnSimpan belum ada listener di initComponents(), tambahkan di sini
        btnClear.addActionListener(e -> clearForm());
        btnSimpan.addActionListener(e -> simpanPenyewaan());

        // Auto-isi tarif ketika kendaraan dipilih
        cmbKendaraan.addActionListener(e -> isiTarifOtomatis());

        muatDataAwal();
    }

    // ===== Helper: ambil id dari string combo berformat "id - kode - label" =====

    private int getIdFromCombo(String selected) {
        if (selected == null || selected.trim().isEmpty()) return -1;
        try {
            return Integer.parseInt(selected.split(" - ")[0].trim());
        } catch (Exception e) {
            return -1;
        }
    }

    private void muatDataAwal() {
        txtNoSewa.setText(Penyewaan.generateNoSewa());
        tglTransaksi.setText(sdfTampil.format(new Date()));

        muatComboPelanggan();
        muatComboKendaraan();
        muatComboSopir();
    }

    private void muatComboPelanggan() {
        cmbPelanggan.removeAllItems();
        String query = "SELECT id_pelanggan, kode_pelanggan, nama_pelanggan FROM pelanggan ORDER BY nama_pelanggan";
        ResultSet rs = DBHelper.selectQuery(query);
        try {
            while (rs != null && rs.next()) {
                String item = rs.getInt("id_pelanggan") + " - " + rs.getString("kode_pelanggan")
                        + " - " + rs.getString("nama_pelanggan");
                cmbPelanggan.addItem(item);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void muatComboKendaraan() {
        cmbKendaraan.removeAllItems();
        String query = "SELECT id_kendaraan, kode_kendaraan, merk, tipe, status FROM kendaraan ORDER BY kode_kendaraan";
        ResultSet rs = DBHelper.selectQuery(query);
        try {
            while (rs != null && rs.next()) {
                String item = rs.getInt("id_kendaraan") + " - " + rs.getString("kode_kendaraan")
                        + " - " + rs.getString("merk") + " " + rs.getString("tipe")
                        + " (" + rs.getString("status") + ")";
                cmbKendaraan.addItem(item);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void muatComboSopir() {
        cmbSopir.removeAllItems();
        cmbSopir.addItem("0 - Tanpa Supir -");
        String query = "SELECT id_sopir, kode_sopir, nama_sopir, status FROM sopir ORDER BY nama_sopir";
        ResultSet rs = DBHelper.selectQuery(query);
        try {
            while (rs != null && rs.next()) {
                String item = rs.getInt("id_sopir") + " - " + rs.getString("kode_sopir")
                        + " - " + rs.getString("nama_sopir") + " (" + rs.getString("status") + ")";
                cmbSopir.addItem(item);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void isiTarifOtomatis() {
        int idKendaraan = getIdFromCombo((String) cmbKendaraan.getSelectedItem());
        if (idKendaraan == -1) return;

        String query = "SELECT tarif_harian, tarif_sopir_harian FROM tarif "
                + "WHERE id_kendaraan = " + idKendaraan + " AND aktif = 1 LIMIT 1";
        ResultSet rs = DBHelper.selectQuery(query);
        try {
            if (rs != null && rs.next()) {
                trfKendaraan.setText(String.valueOf(rs.getDouble("tarif_harian")));
                TrfSupir.setText(String.valueOf(rs.getDouble("tarif_sopir_harian")));
            } else {
                trfKendaraan.setText("");
                TrfSupir.setText("");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private int cariIdTarif(int idKendaraan) {
        int idTarif = 0;
        String query = "SELECT id_tarif FROM tarif WHERE id_kendaraan = " + idKendaraan + " AND aktif = 1 LIMIT 1";
        ResultSet rs = DBHelper.selectQuery(query);
        try {
            if (rs != null && rs.next()) {
                idTarif = rs.getInt("id_tarif");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return idTarif;
    }

    /**
     * Hitung lama hari dari selisih Tanggal Mulai & Tanggal Kembali.
     * Return -1 kalau format salah atau tanggal kembali lebih awal dari tanggal mulai.
     */
    private int hitungLamaHari() {
        try {
            Date mulai = sdfTampil.parse(txtTglMulai.getText().trim());
            Date kembali = sdfTampil.parse(txtTglKembali.getText().trim());
            if (kembali.before(mulai)) {
                return -1;
            }
            long selisihMs = kembali.getTime() - mulai.getTime();
            int hari = (int) (selisihMs / (1000L * 60 * 60 * 24));
            return Math.max(hari, 1);
        } catch (ParseException e) {
            return -1;
        }
    }

    private void tambahKendaraan() {
        int idKendaraan = getIdFromCombo((String) cmbKendaraan.getSelectedItem());
        String kendaraanTerpilih = (String) cmbKendaraan.getSelectedItem();
        String sopirTerpilih = (String) cmbSopir.getSelectedItem();
        int idSopir = getIdFromCombo(sopirTerpilih);

        if (idKendaraan == -1) {
            JOptionPane.showMessageDialog(this, "Pilih kendaraan terlebih dahulu!");
            return;
        }
        if (txtTglMulai.getText().trim().isEmpty() || txtTglKembali.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Isi Tanggal Mulai dan Tanggal Kembali terlebih dahulu!");
            return;
        }

        int lamaHari = hitungLamaHari();
        if (lamaHari == -1) {
            JOptionPane.showMessageDialog(this,
                    "Format tanggal salah (gunakan dd/MM/yyyy), atau Tanggal Mulai lebih awal dari tanggal Kembali",
                    "Validasi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int idTarif = cariIdTarif(idKendaraan);
        if (idTarif == 0) {
            JOptionPane.showMessageDialog(this, "Tarif untuk kendaraan ini belum diatur/tidak aktif!",
                    "Validasi", JOptionPane.WARNING_MESSAGE);
            return;
        }

        double tarifKendaraan;
        double tarifSopir;
        try {
            tarifKendaraan = Double.parseDouble(trfKendaraan.getText().trim());
            tarifSopir = Double.parseDouble(TrfSupir.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Tarif kendaraan tidak valid!");
            return;
        }

        boolean pakaiSopir = idSopir != 0 && idSopir != -1;
        double hargaSopirDipakai = pakaiSopir ? tarifSopir : 0;
        double subtotal = (tarifKendaraan + hargaSopirDipakai) * lamaHari;

        PenyewaanDetail detail = new PenyewaanDetail();
        detail.setIdKendaraan(idKendaraan);
        detail.setIdSopir(pakaiSopir ? idSopir : null);
        detail.setIdTarif(idTarif);
        detail.setLamaHari(lamaHari);
        detail.setHargaSewa(tarifKendaraan);
        detail.setHargaSopir(hargaSopirDipakai);
        detail.setSubtotal(subtotal);
        detail.setKodeKendaraan(kendaraanTerpilih);
        detail.setNamaSopir(pakaiSopir ? sopirTerpilih : "-");

        listDetail.add(detail);

        modelDetail.addRow(new Object[]{
                detail.getKodeKendaraan(),
                detail.getNamaSopir(),
                detail.getLamaHari(),
                detail.getHargaSewa(),
                detail.getHargaSopir(),
                detail.getSubtotal()
        });

        hitungTotal();
    }

    private void hapusKendaraan() {
        int baris = tblDetail.getSelectedRow();
        if (baris == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris kendaraan yang ingin dihapus!");
            return;
        }
        listDetail.remove(baris);
        modelDetail.removeRow(baris);
        hitungTotal();
    }

    private void hitungTotal() {
        double total = 0;
        for (PenyewaanDetail d : listDetail) {
            total += d.getSubtotal();
        }
        txtTotal.setText(String.valueOf(total));
    }

    private void clearForm() {
        txtTglMulai.setText("");
        txtTglKembali.setText("");
        txtCatatan.setText("");
        if (cmbPelanggan.getItemCount() > 0) cmbPelanggan.setSelectedIndex(0);
        if (cmbKendaraan.getItemCount() > 0) cmbKendaraan.setSelectedIndex(0);
        if (cmbSopir.getItemCount() > 0) cmbSopir.setSelectedIndex(0);
        trfKendaraan.setText("");
        TrfSupir.setText("");
        listDetail.clear();
        modelDetail.setRowCount(0);
        txtTotal.setText("");
        txtNoSewa.setText(Penyewaan.generateNoSewa());
    }

    private void simpanPenyewaan() {
        int idPelanggan = getIdFromCombo((String) cmbPelanggan.getSelectedItem());
        if (idPelanggan == -1) {
            JOptionPane.showMessageDialog(this, "Pilih pelanggan terlebih dahulu!");
            return;
        }
        if (txtTglMulai.getText().trim().isEmpty() || txtTglKembali.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tanggal Mulai dan Tanggal Kembali wajib diisi!");
            return;
        }
        if (hitungLamaHari() == -1) {
            JOptionPane.showMessageDialog(this,
                    "Tanggal tidak valid, atau Tanggal Kembali lebih awal dari Tanggal Mulai!",
                    "Validasi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (listDetail.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tambahkan minimal 1 kendaraan!");
            return;
        }

        try {
            Date mulai = sdfTampil.parse(txtTglMulai.getText().trim());
            Date kembali = sdfTampil.parse(txtTglKembali.getText().trim());

            Penyewaan penyewaan = new Penyewaan();
            penyewaan.setNoSewa(txtNoSewa.getText());
            penyewaan.setTglSewa(sdfSql.format(new Date()));
            penyewaan.setIdPelanggan(idPelanggan);
            penyewaan.setTglMulai(sdfSql.format(mulai));
            penyewaan.setTglRencanaKembali(sdfSql.format(kembali));
            penyewaan.setStatus("aktif");
            penyewaan.setCatatan(txtCatatan.getText().trim());

            int idSewaBaru = Penyewaan.simpan(penyewaan);

            if (idSewaBaru == -1) {
                JOptionPane.showMessageDialog(this, "Gagal menyimpan data penyewaan!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            for (PenyewaanDetail d : listDetail) {
                d.setIdSewa(idSewaBaru);
                PenyewaanDetail.simpan(d);

                PenyewaanDetail.updateStatusKendaraan(d.getIdKendaraan(), "disewa");
                if (d.getIdSopir() != null) {
                    PenyewaanDetail.updateStatusSopir(d.getIdSopir(), "bertugas");
                }
            }

            JOptionPane.showMessageDialog(this, "Data penyewaan berhasil disimpan dengan No Sewa: " + penyewaan.getNoSewa());
            clearForm();
            muatComboKendaraan();
            muatComboSopir();

        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Format tanggal tidak valid!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPenyewaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPenyewaan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TrfSupir;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHapusDetail;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambahDetail;
    private javax.swing.JComboBox<String> cmbKendaraan;
    private javax.swing.JComboBox<String> cmbPelanggan;
    private javax.swing.JComboBox<String> cmbSopir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDetail;
    private javax.swing.JTextField tglTransaksi;
    private javax.swing.JTextField trfKendaraan;
    private javax.swing.JTextField txtCatatan;
    private javax.swing.JTextField txtNoSewa;
    private javax.swing.JFormattedTextField txtTglKembali;
    private javax.swing.JFormattedTextField txtTglMulai;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
