/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.DBHelper;
import backend.Penyewaan;
import backend.PenyewaanDetail;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;


/**
 *
 * @author HYPE AMD
 */
public class FrmPenyewaan extends javax.swing.JFrame {
    
    // ===== Field tambahan (di luar bagian generated NetBeans) =====
    private List<PenyewaanDetail> listDetail;
    private DefaultTableModel modelDetail;
    private final SimpleDateFormat sdfTampil = new SimpleDateFormat("dd/MM/yyyy");
    private final SimpleDateFormat sdfSql = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    private final SimpleDateFormat sdfTanggalJam = new SimpleDateFormat("dd/MM/yyyy HH:mm");
    private javax.swing.Timer timerJam;
    private java.text.NumberFormat formatRupiah;
    private final SimpleDateFormat sdfTglMulaiKembali = new SimpleDateFormat("dd/MM/yyyy HH:mm");
    private final SimpleDateFormat sdfJamSaja = new SimpleDateFormat("HH:mm");
    private String waktuMulai = "";
    private String waktuKembali = "";
    private boolean waktuTerkunci = false;
        

    public FrmPenyewaan() {
        initComponents();
        setupTambahan();
    }   
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNoSewa = new javax.swing.JTextField();
        tglTransaksi = new javax.swing.JTextField();
        txtCatatan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        trfKendaraan = new javax.swing.JTextField();
        trfSupir = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetail = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        cmbKendaraan = new javax.swing.JComboBox<>();
        cmbPelanggan = new javax.swing.JComboBox<>();
        cmbSopir = new javax.swing.JComboBox<>();
        btnTambahDetail = new javax.swing.JButton();
        btnHapusDetail = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        txtTglMulai = new javax.swing.JFormattedTextField();
        txtTglKembali = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnClearKendaraan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("No Sewa");

        jLabel2.setText("Tanggal Transaksi");

        jLabel3.setText("Pelanggan");

        jLabel4.setText("Tanggal Mulai");

        jLabel5.setText("Tanggal Kembali");

        jLabel6.setText("Catatan");

        txtNoSewa.setEnabled(false);
        txtNoSewa.addActionListener(this::txtNoSewaActionPerformed);

        tglTransaksi.addActionListener(this::tglTransaksiActionPerformed);

        txtCatatan.addActionListener(this::txtCatatanActionPerformed);

        jLabel7.setText("Kendaraan");

        jLabel8.setText("Sopir");

        jLabel9.setText("Tarif Kendaraan");

        jLabel10.setText("Tarif Supir");

        trfKendaraan.setEnabled(false);
        trfKendaraan.addActionListener(this::trfKendaraanActionPerformed);

        trfSupir.setEnabled(false);

        tblDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDetail.setShowGrid(true);
        jScrollPane1.setViewportView(tblDetail);

        jLabel11.setText("Total");

        txtTotal.addActionListener(this::txtTotalActionPerformed);

        cmbKendaraan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbPelanggan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPelanggan.addActionListener(this::cmbPelangganActionPerformed);

        cmbSopir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnTambahDetail.setText("Tambah Kendaraan");
        btnTambahDetail.addActionListener(this::btnTambahDetailActionPerformed);

        btnHapusDetail.setText("Hapus Kendaraan");
        btnHapusDetail.addActionListener(this::btnHapusDetailActionPerformed);

        btnClear.setText("Clear");

        btnSimpan.setText("Simpan");

        txtTglMulai.addActionListener(this::txtTglMulaiActionPerformed);

        txtTglKembali.addActionListener(this::txtTglKembaliActionPerformed);

        btnClearKendaraan.setText("Clear Kendaraan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtTglMulai, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tglTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(txtCatatan)
                                        .addComponent(txtNoSewa))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtTglKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13))
                                    .addComponent(cmbKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(53, 53, 53)
                                    .addComponent(cmbPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(trfKendaraan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(trfSupir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(cmbSopir, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTambahDetail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapusDetail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClearKendaraan))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(424, 424, 424)
                        .addComponent(jLabel11)
                        .addGap(26, 26, 26)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNoSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tglTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTglMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTglKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtCatatan, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbSopir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trfKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trfSupir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTambahDetail)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnHapusDetail)
                        .addComponent(btnClearKendaraan)))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnClear))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNoSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoSewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoSewaActionPerformed

    private void tglTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglTransaksiActionPerformed

    private void txtCatatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCatatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCatatanActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnTambahDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahDetailActionPerformed
        // TODO add your handling code here:
        tambahKendaraan();
    }//GEN-LAST:event_btnTambahDetailActionPerformed

    private void btnHapusDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusDetailActionPerformed
        // TODO add your handling code here:
        hapusKendaraan();
    }//GEN-LAST:event_btnHapusDetailActionPerformed

    private void trfKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trfKendaraanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trfKendaraanActionPerformed

    private void txtTglKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTglKembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTglKembaliActionPerformed

    private void cmbPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPelangganActionPerformed

    private void txtTglMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTglMulaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTglMulaiActionPerformed

    // ===== Setup tambahan (di luar initComponents, aman dari GUI builder) =====

    private void setupTambahan() {
        formatRupiah = java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("in", "ID"));
        formatRupiah.setMaximumFractionDigits(0);
        formatRupiah.setMinimumFractionDigits(0);
        listDetail = new ArrayList<>();

        // Field read-only
        txtNoSewa.setEditable(false);
        tglTransaksi.setEditable(false);
        trfKendaraan.setEditable(false);
        trfSupir.setEditable(false);
        txtTotal.setEditable(false);

        // Ganti model tabel jadi 6 kolom sesuai kebutuhan
        String[] kolom = {"Kendaraan", "Supir", "Lama Hari", "Tarif Kendaraan", "Tarif Supir", "Subtotal"};
        modelDetail = new DefaultTableModel(kolom, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblDetail.setModel(modelDetail);

        // btnClear & btnSimpan belum ada listener di initComponents(), tambahkan di sini
        btnClear.addActionListener(e -> clearForm());
        btnSimpan.addActionListener(e -> simpanPenyewaan());
        btnClearKendaraan.addActionListener(e -> clearKendaraan());

        // Auto-isi tarif ketika kendaraan dipilih
        cmbKendaraan.addActionListener(e -> isiTarifOtomatis());
        cmbSopir.addActionListener(e -> isiTarifOtomatis());

        muatDataAwal();
        
        // Filter manual: hanya angka, "/" otomatis muncul, khusus tanggal saja
        ((javax.swing.text.AbstractDocument) txtTglMulai.getDocument())
        .setDocumentFilter(new TanggalDocumentFilter());
        ((javax.swing.text.AbstractDocument) txtTglKembali.getDocument())
        .setDocumentFilter(new TanggalDocumentFilter());
        timerJam = new javax.swing.Timer(1000, e -> {
            tglTransaksi.setText(sdfTanggalJam.format(new Date()));
            if (!waktuTerkunci) {
            hitungWaktuOtomatis();
            perbaruiLabelWaktu();
            }
        });
        timerJam.start();
        
        btnClearKendaraan = new javax.swing.JButton("Clear kendaraan");
        btnClearKendaraan.addActionListener(e -> clearKendaraan());
        getContentPane().add(btnClearKendaraan); 
        
        setupComboRenderer();
    }
    
    @Override
    public void dispose() {
    if (timerJam != null) {
        timerJam.stop();
    }
    super.dispose();
    }
    
    // ===== Helper: buang bagian "id - " dari string combo, khusus untuk tampilan =====
    private String hilangkanId(String teks) {
    if (teks == null) return "";
    int idx = teks.indexOf(" - ");
    if (idx != -1) {
        return teks.substring(idx + 3);
    }
    return teks;
    }
    
    // ===== Renderer: sembunyikan id dari tampilan combo, tapi data asli tetap utuh =====
    private void setupComboRenderer() {
    javax.swing.DefaultListCellRenderer renderer = new javax.swing.DefaultListCellRenderer() {
        @Override
        public java.awt.Component getListCellRendererComponent(
                javax.swing.JList<?> list, Object value, int index,
                boolean isSelected, boolean cellHasFocus) {
            super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            if (value != null) {
                String teks = value.toString();
                int idx = teks.indexOf(" - ");
                if (idx != -1) {
                    setText(teks.substring(idx + 3)); // buang bagian "id - "
                }
            }
            return this;
        }
    };
    cmbKendaraan.setRenderer(renderer);
    cmbSopir.setRenderer(renderer);
    }

    // ===== Helper: ambil id dari string combo berformat "id - kode - label" =====

    private int getIdFromCombo(String selected) {
        if (selected == null || selected.trim().isEmpty()) return -1;
        try {
            return Integer.parseInt(selected.split(" - ")[0].trim());
        } catch (Exception e) {
            return -1;
        }
    }
    
    private String formatRupiah(double nilai) {
    return formatRupiah.format(nilai);
    }

    private double parseRupiah(String teks) {
    if (teks == null) return 0;
    String angkaSaja = teks.replaceAll("[^0-9]", "");
    if (angkaSaja.isEmpty()) return 0;
    return Double.parseDouble(angkaSaja);
    }
    
    // Hitung ulang jam otomatis (tidak mengubah tampilan, hanya nilai acuan)
    private void hitungWaktuOtomatis() {
        java.util.Calendar mulai = java.util.Calendar.getInstance();
        mulai.add(java.util.Calendar.HOUR_OF_DAY, 1);
        waktuMulai = sdfJamSaja.format(mulai.getTime());

        java.util.Calendar kembali = (java.util.Calendar) mulai.clone();
        kembali.add(java.util.Calendar.HOUR_OF_DAY, 24);
        waktuKembali = sdfJamSaja.format(kembali.getTime());
    }

    // Kosongkan tampilan tanggal supaya user mengetik manual dari awal
    private void resetTanggalKosong() {
        txtTglMulai.setText("");
        txtTglKembali.setText("");
    }

    // Tampilkan jam otomatis ke label (bukan lagi ke field tanggal)
    private void perbaruiLabelWaktu() {
        jLabel12.setText(waktuMulai);
        jLabel13.setText(waktuKembali);
    }

    private void muatDataAwal() {
        txtNoSewa.setText(Penyewaan.generateNoSewa());
        tglTransaksi.setText(sdfTanggalJam.format(new Date()));

        hitungWaktuOtomatis();
        perbaruiLabelWaktu();
        resetTanggalKosong();
        muatComboPelanggan();
        muatComboKendaraan();
        muatComboSopir();
    }

    private void muatComboPelanggan() {
        cmbPelanggan.removeAllItems();
        String query = "SELECT id_pelanggan, kode_pelanggan, nama_pelanggan FROM pelanggan ORDER BY nama_pelanggan";
        ResultSet rs = DBHelper.selectQuery(query);
        try {
            while (rs != null && rs.next()) {
                String item = rs.getInt("id_pelanggan") + " - " + rs.getString("kode_pelanggan")
                        + " - " + rs.getString("nama_pelanggan");
                cmbPelanggan.addItem(item);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void muatComboKendaraan() {
        cmbKendaraan.removeAllItems();
        String query = "SELECT k.id_kendaraan, k.kode_kendaraan, k.merk, k.tipe, k.status FROM kendaraan k "
            + "WHERE k.status = 'tersedia' "
            + "AND EXISTS (SELECT 1 FROM tarif t WHERE t.id_kendaraan = k.id_kendaraan AND t.aktif = 1) "
            + "ORDER BY k.kode_kendaraan";
        ResultSet rs = DBHelper.selectQuery(query);
        try {
        while (rs != null && rs.next()) {
            String item = rs.getInt("id_kendaraan") + " - " + rs.getString("kode_kendaraan")
                    + " - " + rs.getString("merk") + " " + rs.getString("tipe")
                    + " (" + rs.getString("status") + ")";
            cmbKendaraan.addItem(item);
            }
        } catch (SQLException e) {
        e.printStackTrace();
            }
        }

    private void muatComboSopir() {
        cmbSopir.removeAllItems();
        cmbSopir.addItem("0 - Tanpa Supir -");
        String query = "SELECT id_sopir, kode_sopir, nama_sopir, status FROM sopir " + "WHERE status = 'tersedia' ORDER BY nama_sopir";
        ResultSet rs = DBHelper.selectQuery(query);
        try {
            while (rs != null && rs.next()) {
                String item = rs.getInt("id_sopir") + " - " + rs.getString("kode_sopir")
                        + " - " + rs.getString("nama_sopir") + " (" + rs.getString("status") + ")";
                cmbSopir.addItem(item);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void isiTarifOtomatis() {
        int idKendaraan = getIdFromCombo((String) cmbKendaraan.getSelectedItem());
        if (idKendaraan == -1) return;

        String query = "SELECT tarif_harian, tarif_sopir_harian FROM tarif "
                + "WHERE id_kendaraan = " + idKendaraan + " AND aktif = 1 LIMIT 1";
        ResultSet rs = DBHelper.selectQuery(query);
        try {
            if (rs != null && rs.next()) {
                trfKendaraan.setText(formatRupiah(rs.getDouble("tarif_harian")));

                int idSopir = getIdFromCombo((String) cmbSopir.getSelectedItem());
                if (idSopir <= 0) {
                    trfSupir.setText(formatRupiah(0));
                } else {
                    trfSupir.setText(formatRupiah(rs.getDouble("tarif_sopir_harian")));
                }
            } else {
                trfKendaraan.setText("");
                trfSupir.setText("");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private int cariIdTarif(int idKendaraan) {
        int idTarif = 0;
        String query = "SELECT id_tarif FROM tarif WHERE id_kendaraan = " + idKendaraan + " AND aktif = 1 LIMIT 1";
        ResultSet rs = DBHelper.selectQuery(query);
        try {
            if (rs != null && rs.next()) {
                idTarif = rs.getInt("id_tarif");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return idTarif;
    }

    /**
     * Hitung lama hari dari selisih Tanggal Mulai & Tanggal Kembali.
     * Return -1 kalau format salah atau tanggal kembali lebih awal dari tanggal mulai.
     */
    private int hitungLamaHari() {
        try {
            String teksMulai = txtTglMulai.getText().trim() + " " + jLabel12.getText().trim();
            String teksKembali = txtTglKembali.getText().trim() + " " + jLabel13.getText().trim();
            Date mulai = sdfTglMulaiKembali.parse(teksMulai);
            Date kembali = sdfTglMulaiKembali.parse(teksKembali);
            if (kembali.before(mulai)) {
                return -1;
            }
            long selisihMs = kembali.getTime() - mulai.getTime();
            int hari = (int) Math.ceil(selisihMs / (1000.0 * 60 * 60 * 24));
            return Math.max(hari, 1);
        } catch (ParseException e) {
            return -1;
        }
    }

    private void tambahKendaraan() {
        int idKendaraan = getIdFromCombo((String) cmbKendaraan.getSelectedItem());
        String kendaraanTerpilih = (String) cmbKendaraan.getSelectedItem();
        String sopirTerpilih = (String) cmbSopir.getSelectedItem();
        int idSopir = getIdFromCombo(sopirTerpilih);

        if (idKendaraan == -1) {
            JOptionPane.showMessageDialog(this, "Pilih kendaraan terlebih dahulu!");
            return;
        }
        if (txtTglMulai.getText().trim().isEmpty() || txtTglKembali.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Isi Tanggal Mulai dan Tanggal Kembali terlebih dahulu!");
            return;
        }

        int lamaHari = hitungLamaHari();
        if (lamaHari == -1) {
            JOptionPane.showMessageDialog(this,
                    "Format tanggal salah (gunakan dd/MM/yyyy), atau Tanggal Mulai lebih awal dari tanggal Kembali",
                    "Validasi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int idTarif = cariIdTarif(idKendaraan);
        if (idTarif == 0) {
            JOptionPane.showMessageDialog(this, "Tarif untuk kendaraan ini belum diatur/tidak aktif!",
                    "Validasi", JOptionPane.WARNING_MESSAGE);
            return;
        }

        double tarifKendaraan = parseRupiah(trfKendaraan.getText());
    double tarifSopir = parseRupiah(trfSupir.getText());

    if (tarifKendaraan <= 0) {
    JOptionPane.showMessageDialog(this, "Tarif kendaraan tidak valid!");
    return;
    }

        boolean pakaiSopir = idSopir != 0 && idSopir != -1;
        double hargaSopirDipakai = pakaiSopir ? tarifSopir : 0;
        double subtotal = (tarifKendaraan + hargaSopirDipakai) * lamaHari;

        PenyewaanDetail detail = new PenyewaanDetail();
        detail.setIdKendaraan(idKendaraan);
        detail.setIdSopir(pakaiSopir ? idSopir : null);
        detail.setIdTarif(idTarif);
        detail.setLamaHari(lamaHari);
        detail.setHargaSewa(tarifKendaraan);
        detail.setHargaSopir(hargaSopirDipakai);
        detail.setSubtotal(subtotal);
        detail.setKodeKendaraan(kendaraanTerpilih);
        detail.setNamaSopir(pakaiSopir ? sopirTerpilih : "-");

        listDetail.add(detail);

        modelDetail.addRow(new Object[]{
        hilangkanId(detail.getKodeKendaraan()),
        hilangkanId(detail.getNamaSopir()),
        detail.getLamaHari(),
        formatRupiah(detail.getHargaSewa()),
        formatRupiah(detail.getHargaSopir()),
        formatRupiah(detail.getSubtotal())
});

        hitungTotal();
        
        cmbKendaraan.removeItem(kendaraanTerpilih);
        if (cmbKendaraan.getItemCount()>0) {
            cmbKendaraan.setSelectedIndex(0);
        }
        trfKendaraan.setText("");
        trfSupir.setText("");
        
        txtTglMulai.setEditable(false);
        txtTglKembali.setEditable(false);
        cmbPelanggan.setEnabled(false);
        waktuTerkunci = true;
        if (pakaiSopir){
            cmbSopir.removeItem(sopirTerpilih);
        }
        if (cmbSopir.getItemCount()>0) {
            cmbSopir.setSelectedIndex(0);
        }
        }
    

    private void hapusKendaraan() {
        int baris = tblDetail.getSelectedRow();
        if (baris == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris kendaraan yang ingin dihapus!");
            return;
        }
        PenyewaanDetail detailDihapus = listDetail.get(baris);
        listDetail.remove(baris);
        modelDetail.removeRow(baris);
        hitungTotal();
        cmbKendaraan.addItem(detailDihapus.getKodeKendaraan());
        if (detailDihapus.getIdSopir() !=null) {
            cmbSopir.addItem(detailDihapus.getNamaSopir());
        }
        if (listDetail.isEmpty()){
            txtTglMulai.setEditable(true);
            txtTglKembali.setEditable(true);
            cmbPelanggan.setEnabled(true);
            waktuTerkunci = false;
            hitungWaktuOtomatis();
            perbaruiLabelWaktu();
            resetTanggalKosong();
        }
    }

    private void hitungTotal() {
        double total = 0;
        for (PenyewaanDetail d : listDetail) {
            total += d.getSubtotal();
        }
        txtTotal.setText(formatRupiah(total));
    }

    private void clearForm() {
        waktuTerkunci = false;
        hitungWaktuOtomatis();
        perbaruiLabelWaktu();
        resetTanggalKosong();
        txtTglMulai.setEditable(true);
        txtTglKembali.setEditable(true);
        cmbPelanggan.setEnabled(true);
        txtCatatan.setText("");
        if (cmbPelanggan.getItemCount() > 0) cmbPelanggan.setSelectedIndex(0);
        if (cmbKendaraan.getItemCount() > 0) cmbKendaraan.setSelectedIndex(0);
        if (cmbSopir.getItemCount() > 0) cmbSopir.setSelectedIndex(0);
        trfKendaraan.setText("");
        trfSupir.setText("");
        listDetail.clear();
        modelDetail.setRowCount(0);
        txtTotal.setText("");
        txtNoSewa.setText(Penyewaan.generateNoSewa());
    }
    
    private void clearKendaraan() {
    if (listDetail.isEmpty()) {
        return; // tidak ada apa-apa untuk dihapus
    }

    int konfirmasi = JOptionPane.showConfirmDialog(this,
            "Hapus semua kendaraan yang sudah ditambahkan?",
            "Konfirmasi", JOptionPane.YES_NO_OPTION);
    if (konfirmasi != JOptionPane.YES_OPTION) {
        return;
    }

    for (PenyewaanDetail d : listDetail) {
        cmbKendaraan.addItem(d.getKodeKendaraan());
        if (d.getIdSopir() != null) {
            cmbSopir.addItem(d.getNamaSopir());
        }
    }

        listDetail.clear();
        modelDetail.setRowCount(0);
        txtTotal.setText("");

        txtTglMulai.setEditable(true);
        txtTglKembali.setEditable(true);
        cmbPelanggan.setEnabled(true);
        waktuTerkunci = false;
        hitungWaktuOtomatis();
        perbaruiLabelWaktu();
        resetTanggalKosong();

        }

    private void simpanPenyewaan() {
        int idPelanggan = getIdFromCombo((String) cmbPelanggan.getSelectedItem());
        if (idPelanggan == -1) {
            JOptionPane.showMessageDialog(this, "Pilih pelanggan terlebih dahulu!");
            return;
        }
        if (txtTglMulai.getText().trim().isEmpty() || txtTglKembali.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tanggal Mulai dan Tanggal Kembali wajib diisi!");
            return;
        }
        if (hitungLamaHari() == -1) {
            JOptionPane.showMessageDialog(this,
                    "Tanggal tidak valid, atau Tanggal Kembali lebih awal dari Tanggal Mulai!",
                    "Validasi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (listDetail.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tambahkan minimal 1 kendaraan!");
            return;
        }

        try {
            Date mulai = sdfTglMulaiKembali.parse(txtTglMulai.getText().trim() + " " + jLabel12.getText().trim());
            Date kembali = sdfTglMulaiKembali.parse(txtTglKembali.getText().trim() + " " + jLabel13.getText().trim());

            Penyewaan penyewaan = new Penyewaan();
            penyewaan.setNoSewa(txtNoSewa.getText());
            penyewaan.setTglSewa(sdfSql.format(new Date()));
            penyewaan.setIdPelanggan(idPelanggan);
            penyewaan.setTglMulai(sdfSql.format(mulai));
            penyewaan.setTglRencanaKembali(sdfSql.format(kembali));
            penyewaan.setStatus("aktif");
            penyewaan.setCatatan(txtCatatan.getText().trim());

            int idSewaBaru = Penyewaan.simpan(penyewaan);

            if (idSewaBaru == -1) {
                JOptionPane.showMessageDialog(this, "Gagal menyimpan data penyewaan!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            for (PenyewaanDetail d : listDetail) {
                d.setIdSewa(idSewaBaru);
                PenyewaanDetail.simpan(d);

                PenyewaanDetail.updateStatusKendaraan(d.getIdKendaraan(), "disewa");
                if (d.getIdSopir() != null) {
                    PenyewaanDetail.updateStatusSopir(d.getIdSopir(), "bertugas");
                }
            }

            JOptionPane.showMessageDialog(this, "Data penyewaan berhasil disimpan dengan No Sewa: " + penyewaan.getNoSewa());
            clearForm();
            listDetail.clear();
            modelDetail.setRowCount(0);
            txtTotal.setText("");
            txtTglMulai.setEditable(true);
            txtTglKembali.setEditable(true);
            cmbPelanggan.setEnabled(true);
            waktuTerkunci = false;
            hitungWaktuOtomatis();
            perbaruiLabelWaktu();
            resetTanggalKosong();
            muatComboKendaraan();
            muatComboSopir();

        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Format tanggal tidak valid!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPenyewaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPenyewaan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClearKendaraan;
    private javax.swing.JButton btnHapusDetail;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambahDetail;
    private javax.swing.JComboBox<String> cmbKendaraan;
    private javax.swing.JComboBox<String> cmbPelanggan;
    private javax.swing.JComboBox<String> cmbSopir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDetail;
    private javax.swing.JTextField tglTransaksi;
    private javax.swing.JTextField trfKendaraan;
    private javax.swing.JTextField trfSupir;
    private javax.swing.JTextField txtCatatan;
    private javax.swing.JTextField txtNoSewa;
    private javax.swing.JFormattedTextField txtTglKembali;
    private javax.swing.JFormattedTextField txtTglMulai;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
    
    private static class TanggalDocumentFilter extends javax.swing.text.DocumentFilter {

    @Override
    public void insertString(FilterBypass fb, int offset, String string, javax.swing.text.AttributeSet attr) throws javax.swing.text.BadLocationException {
        replace(fb, offset, 0, string, attr);
    }

    @Override
    public void replace(FilterBypass fb, int offset, int length, String text, javax.swing.text.AttributeSet attrs) throws javax.swing.text.BadLocationException {
        if (text == null) return;

        String existing = fb.getDocument().getText(0, fb.getDocument().getLength());
        StringBuilder sb = new StringBuilder(existing);
        sb.replace(offset, offset + length, text);

        String digits = sb.toString().replaceAll("[^0-9]", "");
        if (digits.length() > 8) {
            digits = digits.substring(0, 8);
        }

        StringBuilder hasil = new StringBuilder();
        
        
        for (int i = 0; i < digits.length(); i++) {
            hasil.append(digits.charAt(i));
            if (i == 1 || i == 3) {
                hasil.append("/");
            }
        }

        fb.remove(0, fb.getDocument().getLength());
        fb.insertString(0, hasil.toString(), attrs);
    }

    @Override
    public void remove(FilterBypass fb, int offset, int length) throws javax.swing.text.BadLocationException {
        fb.remove(offset, length);
        }
    }
    
}
